INSERT INTO TODO(ID, STATUS, TITULO) VALUES (1,'PENDENTE','Estudar SOLID');
INSERT INTO TODO(ID, STATUS, TITULO) VALUES (2,'FINALIZADA','Levar o gato para o veterinário');
INSERT INTO TODO(ID, STATUS, TITULO) VALUES (3,'PENDENTE','Limpar o PC');
INSERT INTO TODO(ID, STATUS, TITULO) VALUES (4,'FINALIZADA','Arrumar o quarto');
INSERT INTO TODO(ID, STATUS, TITULO) VALUES (5,'PENDENTE','Ir nos correios');
INSERT INTO TODO(ID, STATUS, TITULO) VALUES (6,'PENDENTE','Fazer o Projeto');
